GET http://localhost:8000/movies

###

GET http://localhost:8000/movies/67bd71117fc12b3b5de46ed6

###

POST http://localhost:8000/movies 
Content-Type: application/json

{ "title": "Once Upon a Time in Hollywood", "director": "Quentin Tarantino", "release_date": "2019-07-26", "genre": "Comedy, Drama" }

###

DELETE http://localhost:8000/movies/

###

PATCH http://localhost:8000/movies/67bd71117fc12b3b5de46ed6
Content-Type: application/json

{ "title": "New Title", "director": "New Director", "release_date": "2020-01-01", "genre": "Action" }